# 1. Stack two arrays vertically

Use the array given below:

array1 = np.arange(10).reshape(2,-1)

array2 = np.repeat(1, 10).reshape(2,-1)

In [4]:
import numpy as np
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)
print(array1)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
np.concatenate([array1 , array2])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
my_array = np.arange(10,10)
print(my_array)

[]


In [14]:
a=np.arange(24).reshape(4,6)
np.vsplit(a,3)

ValueError: array split does not result in an equal division