In [1]:
import numpy as np

In [2]:
sample_array = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
sample_array [[0,4,7]]

array([10, 14, 17])

In [4]:
sample_array[1:-3]

array([11, 12, 13, 14, 15, 16, 17])

In [26]:
a = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
x=0
b = a[:,x:x+1].sum()
print(a )
print()
print(b)

[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

2


In [12]:
(np.arange(4) + np.arange(4)*5 -5) < 0

array([ True, False, False, False])

In [16]:
sample_array.sum()
np.power(sample_array,1000)

array([          0,  1362851297,           0, -1379469407,           0,
       -2054197887,           0,  -120919423,           0, -2072881503,
                 0], dtype=int32)

In [17]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b
a + 5

array([5, 6, 7])

In [28]:
array_x = np.arange(8)
np.split(array_x , 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [30]:
array_y = np.split(array_x , [5,7])
array_y

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]

In [31]:
import pandas as pd

In [36]:
numbers = range (1,100,5) #list
print(numbers)
pd.Series(numbers) #using the Series Method takes the list and change to Series


range(1, 100, 5)


0      1
1      6
2     11
3     16
4     21
5     26
6     31
7     36
8     41
9     46
10    51
11    56
12    61
13    66
14    71
15    76
16    81
17    86
18    91
19    96
dtype: int64

In [43]:
string = "Hi","How","are" ,"you","?"
x = pd.Series(string)
print(x)
pd.DataFrame(x )

0     Hi
1    How
2    are
3    you
4      ?
dtype: object


0
0   Hi
1  How
2  are
3  you
4    ?

In [57]:
marks = [50,34,56,78,33]
subjects = ["Math","Science","English", "Social Studies" ,"Math"]
x = pd.Series(marks , index = subjects)
print(x)

Math              50
Science           34
English           56
Social Studies    78
Math              33
dtype: int64


In [59]:
1

1

In [52]:
print(x['Math'])
print(x)

Math    50
Math    33
dtype: int64
Math              50
Science           34
English           56
Social Studies    78
Math              33
dtype: int64


In [73]:
subjectDic = {"Maths":13 , "Science":333 , "PE":123 , "Maths":33333}
x = pd.Series(subjectDic)
print (x)

Maths      33333
Science      333
PE           123
dtype: int64


In [74]:
subjects = ["Maths" , "Science" , "Arts" , "PE"]
x= pd.Series(x , index = subjects)
print(x)

Maths      33333.0
Science      333.0
Arts           NaN
PE           123.0
dtype: float64


In [76]:
x.isnull()

Maths      False
Science    False
Arts        True
PE         False
dtype: bool

In [77]:
index=['Apple', 'Banana', 'Orange']
quantity = [34, 20, 30, 40]
pd.Series(data=quantity, index=index)


ValueError: Length of passed values is 4, index implies 3.