In [254]:

# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.20.1


In [259]:
a = np.array(range(10))
a*0
np.zeros(1000)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [273]:
b=np.array([0,2.1,33,4])

In [262]:
np.arange(10,40
         )

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [277]:
x = np.array([4,5])


array([4, 5])

In [17]:
A = np.array([
    [1,2,3],
    [4,5,6],
[3,4,1]])

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, 2])


a = np.arange(4)

In [225]:
a = np.arange(4)
b = np.arange(4)
print (a, b)
a*b

[0 1 2 3] [0 1 2 3]


array([0, 1, 4, 9])

In [218]:
b[[True, False, False, True]]

array([0, 3])

In [230]:

b[~(b>=3)].mean()

1.0

In [238]:
A = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])

In [253]:
B = np.array([
   [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])

In [242]:
A.dot(B)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [243]:
sys.getsizeof(A)

156

In [251]:
sys.getsizeof(1234567890)

32

In [279]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 0.72727896,  0.26006101,  0.31841226],
        [ 0.01668964,  0.37596568,  0.21340906],
        [-1.38203508, -0.08255563, -1.15403007]],

       [[ 1.55684549, -0.25905357,  0.53661139],
        [-1.53383727, -1.73340711,  0.57059445],
        [ 0.9909022 , -0.68978589,  0.58991292]],

       [[ 1.13456108, -0.59728927,  1.03017417],
        [-1.76522505, -0.43747121, -0.3363444 ],
        [ 0.87793619, -0.77246412, -0.55605718]]])

In [281]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

In [287]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[1::2]

array(['B', 'D'], dtype='<U1')

In [288]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

In [289]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [295]:
X = [-5, -3, 0, 10, 40]

np.array(X[<0])

SyntaxError: invalid syntax (<ipython-input-295-b2e0be4bb02a>, line 3)

In [296]:
l = list(range(100000))

In [297]:
a = np.arange(100000)

In [298]:
%time np.sum(a ** 2)

Wall time: 500 µs


216474736

In [299]:

%time sum([x ** 2 for x in l])

Wall time: 35 ms


333328333350000

In [300]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [303]:
np.linspace(1, 11, 10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [304]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [305]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [308]:
np.eye(8, 4, k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [309]:
"Hello World"[6]

'W'