#### 1. Write a code to divide the array into three sub-arrays containing an equal number of rows

Use the array given below:

A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [5]:
import numpy as np
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
A = np.array(A)

# split the array into 3 sub-arrays containing two rows each

np.array_split(A,3)


[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

	
#### 2.  Write a program to divide the array into two sub-arrays containing an equal number of columns

Use the array given below:

B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [16]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
B = np.array(B)
# split the array into two sub-arrays containing two rows each
np.array_split(B,2)


[array([[ 8,  7,  0,  9],
        [ 2, -3,  5, 10]]),
 array([[ 8,  5, -1,  3]])]

In [20]:
np.split(B.reshape(2,6),2)

[array([[ 8,  7,  0,  9,  2, -3]]), array([[ 5, 10,  8,  5, -1,  3]])]

In [24]:
import pandas as pd
a1 = ['Hogwarts', 'Durmstrang', 'Beauxbatons']
a2 = ['Hogwarts', 'Durmstrang', 'Beauxbatons']
a3 = ['Hogwarts', 'Durmstrang', 'Beauxbatons']
school = [a1, a2, a3]
inst = ['School_1', 'School_2', 'School_3']
Muggle_data = pd.DataFrame(data=school, columns=inst)
print(Muggle_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   School_1  3 non-null      object
 1   School_2  3 non-null      object
 2   School_3  3 non-null      object
dtypes: object(3)
memory usage: 200.0+ bytes
None
